import { Injectable } from '@angular/core';
import { agnre } from 'src/app/Models/rutinas/DesarrolloCognitivo/Recuperacion/agnre.model';

@Injectable({
  providedIn: 'root'
})

export class AGNRE2012Service {

  public banderas:Array<agnre>;
/* 
      public imagen: string,
      public imagenBN: string,
      public opcion1: string,
      public opcion2: string,
      public nombre: string,
      public estado: string,
*/
  constructor(){
      this.banderas = [
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Alemania.png','../assets/img/rutinas/desarrolloCognitivo/agnre/AlemaniaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Alemania01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Alemania02.png','Alemania'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Antigua.png','../assets/img/rutinas/desarrolloCognitivo/agnre/AntiguaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Antigua01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Antigua02.png','Antigua y Barbuda'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Argentina.png','../assets/img/rutinas/desarrolloCognitivo/agnre/ArgentinaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Argentina01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Argentina02.png','Argentina'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Armenia.png','../assets/img/rutinas/desarrolloCognitivo/agnre/ArmeniaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Armenia01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Armenia02.png','Armenia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Austria.png','../assets/img/rutinas/desarrolloCognitivo/agnre/AustriaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Austria01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Austria02.png','Austria'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Bahamas.png','../assets/img/rutinas/desarrolloCognitivo/agnre/BahamasBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Bahamas01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Bahamas02.png','Bahamas'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/banderas-06.png','../assets/img/rutinas/desarrolloCognitivo/agnre/banderas-06BN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/banderas-07.png','../assets/img/rutinas/desarrolloCognitivo/agnre/banderas-08.png','Perú'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Barbados.png','../assets/img/rutinas/desarrolloCognitivo/agnre/BarbadosBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Barbados01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Barbados02.png','Barbados'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Belgica.png','../assets/img/rutinas/desarrolloCognitivo/agnre/BelgicaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Belgica01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Belgica02.png','Bélgica'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Bolivia.png','../assets/img/rutinas/desarrolloCognitivo/agnre/BoliviaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Bolivia01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Bolivia02.png','Bolivia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Brasil.png','../assets/img/rutinas/desarrolloCognitivo/agnre/BrasilBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Brasil01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Brasil02.png','Brasil'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Bulgaria.png','../assets/img/rutinas/desarrolloCognitivo/agnre/BulgariaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Bulgaria01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Bulgaria02.png','Bulgaria'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Canada.png','../assets/img/rutinas/desarrolloCognitivo/agnre/CanadaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Canada01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Canada02.png','Canadá'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Chile.png','../assets/img/rutinas/desarrolloCognitivo/agnre/ChileBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Chile01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Chile02.png','Chile'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Colombia.png','../assets/img/rutinas/desarrolloCognitivo/agnre/ColombiaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Colombia01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Colombia02.png','Colombia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Cuba.png','../assets/img/rutinas/desarrolloCognitivo/agnre/CubaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Cuba01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Cuba02.png','Cuba'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Dinamarca.png','../assets/img/rutinas/desarrolloCognitivo/agnre/DinamarcaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Dinamarca01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Dinamarca02.png','Dinamarca'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Ecuador.png','../assets/img/rutinas/desarrolloCognitivo/agnre/EcuadorBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Ecuador01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Ecuador02.png','Ecuador'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/El Salvador.png','../assets/img/rutinas/desarrolloCognitivo/agnre/El SalvadorBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/El Salvador01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/El Salvador02.png','El Salvador'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Emiratos Árabes.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Emiratos ÁrabesBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Emiratos Árabes01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Emiratos Árabes02.png','Emiratos Árabes'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Francia.png','../assets/img/rutinas/desarrolloCognitivo/agnre/FranciaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Francia01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Francia02.png','Francia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Granada.png','../assets/img/rutinas/desarrolloCognitivo/agnre/GranadaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Granada01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Granada02.png','Granada'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Grecia.png','../assets/img/rutinas/desarrolloCognitivo/agnre/GreciaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Grecia01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Grecia02.png','Grecia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Guyana Francesa.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Guyana FrancesaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Guyana Francesa01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Guyana Francesa02.png','Guyana Francesa'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Guyana.png','../assets/img/rutinas/desarrolloCognitivo/agnre/GuyanaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Guyana01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Guyana02.png','Guyana'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Haiti.png','../assets/img/rutinas/desarrolloCognitivo/agnre/HaitiBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Haiti01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Haiti02.png','Haití'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Holanda.png','../assets/img/rutinas/desarrolloCognitivo/agnre/HolandaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Holanda01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Holanda02.png','Holanda'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Honduras.png','../assets/img/rutinas/desarrolloCognitivo/agnre/HondurasBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Honduras01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Honduras02.png','Honduras'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Hungria.png','../assets/img/rutinas/desarrolloCognitivo/agnre/HungriaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Hungria01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Hungria02.png','Hungría'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Inglaterra.png','../assets/img/rutinas/desarrolloCognitivo/agnre/InglaterraBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Inglaterra01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Inglaterra02.png','Inglaterra'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Irlanda.png','../assets/img/rutinas/desarrolloCognitivo/agnre/IrlandaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Irlanda01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Irlanda02.png','Irlanda'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Italia.png','../assets/img/rutinas/desarrolloCognitivo/agnre/ItaliaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Italia01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Italia02.png','Italia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Jamaica.png','../assets/img/rutinas/desarrolloCognitivo/agnre/JamaicaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Jamaica01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Jamaica02.png','Jamaica'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Kuwait.png','../assets/img/rutinas/desarrolloCognitivo/agnre/KuwaitBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Kuwait01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Kuwait02.png','Kuwait'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Letonia.png','../assets/img/rutinas/desarrolloCognitivo/agnre/LetoniaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Letonia01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Letonia02.png','Letonia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Lituania.png','../assets/img/rutinas/desarrolloCognitivo/agnre/LituaniaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Lituania01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Lituania02.png','Lituania'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Luxemburgo.png','../assets/img/rutinas/desarrolloCognitivo/agnre/LuxemburgoBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Luxemburgo01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Luxemburgo02.png','Luxemburgo'),        
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-58.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-58BN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-59.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-60.png','Noruega'),        
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-64.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-64BN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-65.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-66.png','Finlandia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-67.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-67BN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-68.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-69.png','República Checa'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-73.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-73BN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-74.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-75.png','Georgia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-76.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-76BN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-77.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-78.png','Estonia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-82.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-82BN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-83.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Masbanderolas-84.png','Escocia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/México.png','../assets/img/rutinas/desarrolloCognitivo/agnre/MéxicoBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/México01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/México02.png','México'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Monaco.png','../assets/img/rutinas/desarrolloCognitivo/agnre/MonacoBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Monaco01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Monaco02.png','Mónaco'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Nicaragua.png','../assets/img/rutinas/desarrolloCognitivo/agnre/NicaraguaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Nicaragua01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Nicaragua02.png','Nicaragua'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Palestina.png','../assets/img/rutinas/desarrolloCognitivo/agnre/PalestinaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Palestina01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Palestina02.png','Palestina'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Panamá.png','../assets/img/rutinas/desarrolloCognitivo/agnre/PanamáBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Panamá01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Panamá02.png','Panamá'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Paraguay.png','../assets/img/rutinas/desarrolloCognitivo/agnre/ParaguayBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Paraguay01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Paraguay02.png','Paraguay'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Polonia.png','../assets/img/rutinas/desarrolloCognitivo/agnre/PoloniaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Polonia01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Polonia02.png','Polonia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Puerto Rico.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Puerto RicoBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Puerto Rico01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Puerto Rico02.png','Puerto Rico'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Republica Dominicana.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Republica DominicanaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Republica Dominicana01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Republica Dominicana02.png','República Dominicana'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Rumania.png','../assets/img/rutinas/desarrolloCognitivo/agnre/RumaniaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Rumania01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Rumania02.png','Rumania'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Rusia.png','../assets/img/rutinas/desarrolloCognitivo/agnre/RusiaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Rusia01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Rusia02.png','Rusia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/San Eustaquio.png','../assets/img/rutinas/desarrolloCognitivo/agnre/San EustaquioBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/San Eustaquio01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/San Eustaquio02','San Eustaquio'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/San Kitts.png','../assets/img/rutinas/desarrolloCognitivo/agnre/San KittsBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/San Kitts01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/San Kitss02.png','San Kitts'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/San Vicente.png','../assets/img/rutinas/desarrolloCognitivo/agnre/San VicenteBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/San Vicente01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/San Vicente02.png','San Vicente'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Santa Lucía.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Santa LucíaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Santa Lucía01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Santa Lucía02.png','Santa Lucía'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Suecia.png','../assets/img/rutinas/desarrolloCognitivo/agnre/SueciaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Suecia01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Suecia02.png','Suecia'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Surinam.png','../assets/img/rutinas/desarrolloCognitivo/agnre/SurinamBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Surinam01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Surinam02.png','Surinam'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Trinidad y Tobago.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Trinidad y TobagoBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Trinidad y Tobago01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Trinidad y Tobago02.png','Trinidad y Tobago'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Ucrania.png','../assets/img/rutinas/desarrolloCognitivo/agnre/UcraniaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Ucrania01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Ucrania02.png','Ucrania'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Uruguay.png','../assets/img/rutinas/desarrolloCognitivo/agnre/UruguayBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Uruguay01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Uruguay02.png','Uruguay'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/USA.png','../assets/img/rutinas/desarrolloCognitivo/agnre/USABN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/USA01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/USA02.png','Estados Unidos'),
        new agnre('../assets/img/rutinas/desarrolloCognitivo/agnre/Venezuela.png','../assets/img/rutinas/desarrolloCognitivo/agnre/VenezuelaBN.png',
        '../assets/img/rutinas/desarrolloCognitivo/agnre/Venezuela01.png','../assets/img/rutinas/desarrolloCognitivo/agnre/Venezuela02.png','Venezuela'),
        ];

  }
  ngonInit(){
  }
  getBanderas(){
      return this.banderas;
  }
}
