import { Injectable } from '@angular/core';
import { egnre } from 'src/app/Models/rutinas/DesarrolloCognitivo/Recuperacion/egnre.model';

@Injectable({
  providedIn: 'root'
})
export class EGNRE1012Service {
  public banderas:Array<egnre>;

  constructor(){
      this.banderas = [
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/afganistan.jpg','Afganistán',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/aland.jpg','Åland',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/albania.jpg','Albania',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/alemania.jpg','Alemania',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/andorra.jpg','Andorra',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/angola.jpg','Angola',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/anguila.jpg','Anguila',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/arabiaSaudita.jpg','Arabia saudita',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/argelia.jpg','Argelia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/argentina.jpg','Argentina',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/armenia.jpg','Armenia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/aruba.jpg','Aruba',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/australia.jpg','Australia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/azerbaiyan.jpg','Azerbaiyán',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/bahamas.jpg','Bahamas',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/banglades.jpg','Bangladesh',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/barbados.jpg','Barbados',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/barein.jpg','Baréin',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/belgica.jpg','Bélgica',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/belice.jpg','Belice',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/bermudas.jpg','Bermudas',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/bielorrusia.jpg','Bielorrusia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/bolivia.jpg','Bolivia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/botsuana.jpg','Botsuana',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/brasil.jpg','Brasil',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/brunei.jpg','Brunéi',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/bulgaria.jpg','Bulgaria',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/burkinaFaso.jpg','Burkina Faso',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/butan.jpg','Bután',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/caboVerde.jpg','Cabo Verde',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/camboya.jpg','Camboya',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/camerun.jpg','Camerún',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/canada.jpg','Canadá',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/catar.jpg','Catar',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/chad.jpg','Chad',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/chile.jpg','Chile',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/china.jpg','China',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/chipre.jpg','Chipre',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/colombia.jpg','Colombia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/comoras.jpg','Comoras',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/coreaDelNorte.jpg','Corea del Norte',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/coreaDelSur.jpg','Corea del Sur',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/costaDeMarfil.jpg','Costa de Marfil',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/costaRica.jpg','Costa Rica',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/croacia.jpg','Croacia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/cuba.jpg','Cuba',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/dinamarca.jpg','Dinamarca',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/ecuador.jpg','Ecuador',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/egipto.jpg','Egipto',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/elSalvador.jpg','El salvador',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/emiratosArabesUnidos.jpg','Emiratos Árabes Unidos',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/escocia.jpg','Escocia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/eslovaquia.jpg','Eslovaquia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/eslovenia.jpg','Eslovenia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/españa.jpg','España',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/estadosUnidos.jpg','Estados Unidos',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/etiopia.jpg','Etiopía',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/filipinas.jpg','Filipinas',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/finlandia.jpg','Finlandia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/francia.jpg','Francia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/gales.jpg','Gales',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/georgia.jpg','Georgia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/ghana.jpg','Ghana',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/grecia.jpg','Grecia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/guatemala.jpg','Guatemala',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/guinea.jpg','Guinea',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/guyana.jpg','Guyana',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/haiti.jpg','Haití',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/honduras.jpg','Honduras',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/hungria.jpg','Hungría',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/india.jpg','India',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/inglaterra.jpg','Inglaterra',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/irak.jpg','Irak',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/iran.jpg','Iran',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/irlanda.jpg','Irlanda',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/islandia.jpg','Islandia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/israel.jpg','Israel',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/italia.jpg','Italia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/jamaica.jpg','Jamaica',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/japon.jpg','Japón',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/jordania.jpg','Jordania',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/kenia.jpg','Kenia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/kuwait.jpg','Kuwait',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/liberia.jpg','Liberia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/libia.jpg','Libia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/madagascar.jpg','Madagascar',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/malasia.jpg','Malasia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/mexico.jpg','México',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/nicaragua.jpg','Nicaragua',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/noruega.jpg','Noruega',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/pakistan.jpg','Pakistán',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/panama.jpg','Panamá',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/peru.jpg','perú',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/portugal.jpg','Portugal',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/puertoRico.jpg','Puerto rico',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/reinoUnido.jpg','Reino unido',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/republicaCheca.jpg','República Checa',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/republicaDominicana.jpg','República Dominicana',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/rusia.jpg','Rusia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/santaLucia.jpg','Santa Lucía',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/sanVicente.jpg','San vicente',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/serbia.jpg','Serbia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/singapur.jpg','Singapur',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/siria.jpg','Siria',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/sudafrica.jpg','Sudáfrica',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/sudan.jpg','Sudán',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/suecia.jpg','Suecia',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/surinam.jpg','Surinam',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/tunez.jpg','Túnez',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/turquia.jpg','Turquía',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/uruguay.jpg','Uruguay',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/venezuela.jpg','Venezuela',''),
        new egnre ('../assets/img/rutinas/desarrolloCognitivo/banderas/vietnam.jpg','Vietnam','')
      ];
  }
  ngonInit(){
  }
  getBanderas(){
      return this.banderas;
  }
}
